// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { RootDto } from "@/src/testing/dto/root.ts";
import { RunnerStatusDto } from "@/src/testing/dto/runner-status.ts";
import { assert } from "#assert";
import { Runner } from "@/src/testing/domain/business/runner/mod.ts";
import { Runner as RunnerData } from "@/src/testing/domain/data/runner/mod.ts";

// Coordinator for [REQ] runner.ensure(RootDto): RunnerStatusDto.
export async function ensure(input: RootDto): Promise<RunnerStatusDto> {
  const validInput = assert(RootDto, input, "runner.ensure input");
  const runnerData = new RunnerData();

  // reads — load inputs through the data adapters (validated at the seam)
  const runnerProvision = assert(
    RunnerStatusDto,
    await runnerData.provision(validInput.projectRoot),
    "runner.provision",
  );

  // core — pure business logic, no I/O
  const out = ensureCore(validInput, runnerProvision);

  return assert(RunnerStatusDto, out.result, "runner.ensure output");
}

// Pure business logic for runner.ensure — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function ensureCore(
  input: RootDto,
  runnerProvision: RunnerStatusDto,
): { result: RunnerStatusDto } {
  const runner = new Runner();
  return { result: runner.collect(runnerProvision) };
}
