// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { RootDto } from "@/src/discovery/dto/root.ts";
import { ManifestDto } from "@/src/discovery/dto/manifest.ts";
import { DiscoverResultDto } from "@/src/discovery/dto/discover-result.ts";
import { assert } from "#assert";
import { Manifest } from "@/src/discovery/domain/business/manifest/mod.ts";
import { Project as ProjectData } from "@/src/discovery/domain/data/project/mod.ts";

// Coordinator for [REQ] manifest.build(RootDto): ManifestDto.
export async function build(input: RootDto): Promise<ManifestDto> {
  const validInput = assert(RootDto, input, "manifest.build input");
  const projectData = new ProjectData();

  // reads — load inputs through the data adapters (validated at the seam)
  const projectScan = assert(
    DiscoverResultDto,
    await projectData.scan(validInput.projectRoot),
    "project.scan",
  );

  // core — pure business logic, no I/O
  const out = buildCore(validInput, projectScan);

  return assert(ManifestDto, out.result, "manifest.build output");
}

// Pure business logic for manifest.build — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function buildCore(
  input: RootDto,
  projectScan: DiscoverResultDto,
): { result: ManifestDto } {
  const manifest = new Manifest();
  return { result: manifest.fromDiscovery(projectScan).toDto() };
}
