// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { RootDto } from "@/src/discovery/dto/root.ts";
import { DiscoverResultDto } from "@/src/discovery/dto/discover-result.ts";
import { assert } from "#assert";
import { Discovery } from "@/src/discovery/domain/business/discovery/mod.ts";
import { Project as ProjectData } from "@/src/discovery/domain/data/project/mod.ts";

// Coordinator for [REQ] discovery.scan(RootDto): DiscoverResultDto.
export async function scan(input: RootDto): Promise<DiscoverResultDto> {
  const validInput = assert(RootDto, input, "discovery.scan input");
  const projectData = new ProjectData();

  // reads — load inputs through the data adapters (validated at the seam)
  const projectScan = assert(
    DiscoverResultDto,
    await projectData.scan(validInput.projectRoot),
    "project.scan",
  );

  // core — pure business logic, no I/O
  const out = scanCore(validInput, projectScan);

  return assert(DiscoverResultDto, out.result, "discovery.scan output");
}

// Pure business logic for discovery.scan — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function scanCore(
  input: RootDto,
  projectScan: DiscoverResultDto,
): { result: DiscoverResultDto } {
  const discovery = new Discovery();
  return { result: discovery.collect(projectScan) };
}
