// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsOptional,
  IsString,
  ValidateNested,
} from "class-validator";
import { ProblemDto } from "@/src/testing/dto/problem.ts";
import { TestResultDto } from "@/src/testing/dto/test-result.ts";

// the aggregate report a run returns
export class TestReportDto {
  @IsBoolean()
  ok!: boolean;

  @IsBoolean()
  ran!: boolean;

  @IsNumber()
  total!: number;

  @IsNumber()
  passed!: number;

  @IsNumber()
  failed!: number;

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TestResultDto)
  testResults?: TestResultDto[];

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ProblemDto)
  problems?: ProblemDto[];

  @IsOptional()
  @IsString()
  error?: string;
}
