// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import {
  Endpoint,
  EndpointController,
  endpointModule,
} from "@techgoose-labs/rune";
import { TestRunRequestDto } from "@/src/testing/dto/test-run-request.ts";
import { TestReportDto } from "@/src/testing/dto/test-report.ts";
import { RootDto } from "@/src/testing/dto/root.ts";
import { RunnerStatusDto } from "@/src/testing/dto/runner-status.ts";
import { run as testRun } from "@/src/testing/domain/coordinators/test-run/mod.ts";
import { ensure as runnerEnsure } from "@/src/testing/domain/coordinators/runner-ensure/mod.ts";

// The workbench is a local dev tool with no login system — the browser UI's
// ▸ run buttons call these routes directly. Under rune 6's zero-built-in-auth model
// routes are open by default (the old @Public() decorator that opted them out of
// keep's fail-closed guard no longer exists, or exports).
@EndpointController("http")
export class HttpController {
  @Endpoint({
    path: "post-test-run",
    input: TestRunRequestDto,
    output: TestReportDto,
    order: 1,
  })
  postTestRun(body: TestRunRequestDto): Promise<TestReportDto> {
    return testRun(body);
  }

  @Endpoint({
    path: "get-runner-status",
    input: RootDto,
    output: RunnerStatusDto,
    order: 2,
  })
  getRunnerStatus(body: RootDto): Promise<RunnerStatusDto> {
    return runnerEnsure(body);
  }
}

export const httpModule = endpointModule("Testing", [HttpController]);
