// BEDROCK_SERVE_MARKER — the composition root at the git root.
//
// One call composes the app: every dispatch enters the root, so the guard
// covers every channel and every cross-unit call is instrumented.
//
//   deno serve -A serve.ts     (add --env-file=.env if a unit reads one)
//
// UI-only: no backend composed, so `inject(Backend)` fails loud and there is
// nothing serving `/api/*`. The route guards still run — they are the SSR app's.
//
// Regenerated by the toolchain's init — write app code in a unit, not here.
import { Bedrock } from "@techgoose-labs/bedrock";
import { Frontend } from "@techgoose-labs/sprig/bedrock";
import { sprigApp } from "./src/mod.ts";

export default Bedrock({ ui: Frontend({ app: sprigApp }) });
