// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Domain nouns (from [NON]):
//   project: the host Fresh project being scanned for isolate/ folders
//
// Type vocabulary (from [TYP]):
//   projectRoot: string — host project root to scan; defaults to the server's cwd
//   slug: string — root-qualified id, e.g. islands__counter
//   label: string — human label (the folder name)
//   kind: string — "static" or "island"
//   sourceRoot: string — source root: components, islands, or pages
//   target: string — "component" or "page"
//   dir: string — absolute path to the component directory
//   isolateDir: string — absolute path to the isolate/ folder
//   componentFile: string — resolved .tsx file for the component (or "")
//   exportName: string — PascalCase export expected from componentFile
//   category: string — gallery group + URL segment
//   folder: string — optional sub-group + URL segment ("" when absent)
//   background: string — stage background behind the component
//   controlDefs: Record<string, unknown> — top-level control widget definitions, keyed by prop name
//   subControlDefs: Record<string, unknown> — per-sub-component control defs, keyed by function name
//   name: string — a case or test name
//   jsonPath: string — absolute path to the case JSON file
//   props: Record<string, unknown> — bare-key props passed to the component
//   innerHtml: string — children via dangerouslySetInnerHTML
//   signals: Record<string, unknown> — signal-typed values, keyed by name
//   mocks: Record<string, unknown> — sub-component mock/force directives, keyed by name
//   route: string — preview route, e.g. /components/buttons/primary
//   file: string — absolute file path
//   path: string — the offending file or directory for a problem
//   detail: string — human-readable explanation of a problem
//
// Backing services (from [SRV]):
//   fs (sc): ISOLATE_ROOT
// Public API surface for module "discovery".

export { scan } from "./domain/coordinators/discovery-scan/mod.ts";

export { build } from "./domain/coordinators/manifest-build/mod.ts";
