// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata"; // must load before the controller decorates (nested @Type DTOs)
import { httpModule } from "./mod.ts";
import { bootstrapServer, exerciseEndpoints } from "@techgoose-labs/rune";
import { assertEquals } from "#std/assert";

// Fill the coordinator bodies, then run with RUNE_E2E=1 to drive every endpoint
// to green (orders by @Endpoint order, chains outputs into inputs via bind).
Deno.test({
  name: "discovery/http — endpoints run and chain",
  ignore: !Deno.env.get("RUNE_E2E"),
  fn: async () => {
    const api = await bootstrapServer("discovery", httpModule, {
      swagger: true,
    });
    try {
      const report = await exerciseEndpoints({ api });
      assertEquals(report.failed.map((r) => r.id), []);
    } finally {
      await api.stop();
    }
  },
});
