// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import {
  Endpoint,
  EndpointController,
  endpointModule,
} from "@techgoose-labs/rune";
import { RootDto } from "@/src/discovery/dto/root.ts";
import { DiscoverResultDto } from "@/src/discovery/dto/discover-result.ts";
import { ManifestDto } from "@/src/discovery/dto/manifest.ts";
import { scan as discoveryScan } from "@/src/discovery/domain/coordinators/discovery-scan/mod.ts";
import { build as manifestBuild } from "@/src/discovery/domain/coordinators/manifest-build/mod.ts";

// The workbench is a local dev tool with no login system — the browser UI's
// sidebar/navigator reads discovery straight off these routes. Under rune 6's
// zero-built-in-auth model routes are open by default (the old @Public() decorator
// that opted them out of keep's fail-closed guard no longer exists, or exports).
@EndpointController("http")
export class HttpController {
  @Endpoint({
    path: "get-discovery",
    input: RootDto,
    output: DiscoverResultDto,
    order: 1,
  })
  getDiscovery(body: RootDto): Promise<DiscoverResultDto> {
    return discoveryScan(body);
  }

  @Endpoint({
    path: "get-manifest",
    input: RootDto,
    output: ManifestDto,
    order: 2,
  })
  getManifest(body: RootDto): Promise<ManifestDto> {
    return manifestBuild(body);
  }
}

export const httpModule = endpointModule("Discovery", [HttpController]);
