// Generated by rune manifest from testing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { TestRunRequestDto } from "@/src/testing/dto/test-run-request.ts";
import { TestReportDto } from "@/src/testing/dto/test-report.ts";
import { assert } from "#assert";
import { Test } from "@/src/testing/domain/business/test/mod.ts";
import { Runner as RunnerData } from "@/src/testing/domain/data/runner/mod.ts";

// Coordinator for [REQ] test.run(TestRunRequestDto): TestReportDto.
export async function run(input: TestRunRequestDto): Promise<TestReportDto> {
  const validInput = assert(TestRunRequestDto, input, "test.run input");
  const runnerData = new RunnerData();

  // reads — load inputs through the data adapters (validated at the seam)
  const runnerRun = assert(
    TestReportDto,
    await runnerData.run(validInput),
    "runner.run",
  );

  // core — pure business logic, no I/O
  const out = runCore(validInput, runnerRun);

  return assert(TestReportDto, out.result, "test.run output");
}

// Pure business logic for test.run — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function runCore(
  input: TestRunRequestDto,
  runnerRun: TestReportDto,
): { result: TestReportDto } {
  const test = new Test();
  return { result: test.collect(runnerRun) };
}
