// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import {
  Allow,
  IsArray,
  IsOptional,
  IsString,
  ValidateNested,
} from "class-validator";
import { TestDto } from "@/src/discovery/dto/test.ts";

// one preview scenario for a component
export class CaseDto {
  @IsString()
  name!: string;

  @IsString()
  label!: string;

  @IsString()
  jsonPath!: string;

  @Allow()
  props!: Record<string, unknown>;

  @IsOptional()
  @IsString()
  innerHtml?: string;

  @IsOptional()
  @Allow()
  signals?: Record<string, unknown>;

  @IsOptional()
  @Allow()
  mocks?: Record<string, unknown>;

  @IsString()
  route!: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TestDto)
  tests!: TestDto[];
}
