// Generated by rune manifest from discovery.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import {
  Allow,
  IsArray,
  IsOptional,
  IsString,
  ValidateNested,
} from "class-validator";
import { CaseDto } from "@/src/discovery/dto/case.ts";

// a discovered component, island, or page composition
export class EntryDto {
  @IsString()
  slug!: string;

  @IsString()
  label!: string;

  @IsString()
  kind!: string;

  @IsString()
  sourceRoot!: string;

  @IsString()
  target!: string;

  @IsString()
  dir!: string;

  @IsString()
  isolateDir!: string;

  @IsString()
  componentFile!: string;

  @IsString()
  exportName!: string;

  @IsString()
  category!: string;

  @IsString()
  folder!: string;

  @IsOptional()
  @IsString()
  background?: string;

  @Allow()
  controlDefs!: Record<string, unknown>;

  @Allow()
  subControlDefs!: Record<string, unknown>;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CaseDto)
  cases!: CaseDto[];
}
